(function(scope){
 'use strict';
 const D=typeof require==='function'?require('./trail-seasons.js'):scope.ExploreSeasons;
 const T=typeof require==='function'?require('../trail-discovery.js'):scope.TrailDiscovery;
 const name=f=>f.properties.name||'Unnamed feature',source=f=>f.properties.rec1stop_url||f.properties.usda_portal_url||f.properties.evidence?.source_url;
 const sourceType=f=>String(f.properties.site_type||'').toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase());
 // Free text copied from a source row is shown only where an agency page exists to compare it against.
 const agencyPage=f=>f.properties.rec1stop_url||f.properties.usda_portal_url,DESCRIPTIVE=['important_info','activity_type_list','directions'],WITHHELD='Descriptive text from the source is withheld: it cannot be tied to an agency page for this place.';
 const withheld=f=>!f.properties.activities&&!agencyPage(f)&&DESCRIPTIVE.some(key=>f.properties[key]&&f.properties[key]!=='No Data');
 const kind=f=>f.properties.activities?'Trail segment':f.properties.site_type==='TRAILHEAD'?'Trailhead':f.properties.site_type==='DISPERSED_AREA'?'Dispersed camping area':f.properties.site_type==='CAMPGROUND'?'Campground':sourceType(f);
 function rows(trails,sites,area,mode,query,activity){const q=query.toLowerCase().trim();return mode==='trails'?trails.filter(f=>T.matches(f,q,activity)):(mode==='camping'?[...(area?[area]:[]),...D.camping(sites)]:mode==='trailheads'?sites.filter(f=>f.properties.site_type==='TRAILHEAD'):mode==='other-sites'?sites.filter(f=>!['CAMPGROUND','TRAILHEAD','DISPERSED_AREA'].includes(f.properties.site_type)):[]).filter(f=>name(f).toLowerCase().includes(q));}
 function buildPlan(records,saved,trip,notes,exportedAt){return {exported_at:exportedAt,trip,saved:saved.map(id=>{const f=records.get(id);return {id,name:name(f),type:kind(f),source:source(f),source_fetched:f.properties.evidence?.retrieved_at};}),notes,limitations:'Research only. Closures, road connections, camping permission, vehicle suitability and availability are unconfirmed.'};}
 function attach(shell){
  const {element:el,button,$}=shell,region=shell.region,caps=region.config.capabilities,keys=region.config.storage_keys,M=scope.ExploreMap,E=scope.ExploreEvidence;
  const trailEntry=region.registry.find(x=>x.kind==='trails'),siteEntry=region.registry.find(x=>x.kind==='recreation_sites');
  const trails=()=>region.layers.get(trailEntry.id)?.data?.features||[],sites=()=>region.layers.get(siteEntry.id)?.data?.features||[];
  const area=shell.extras?.area;
  let saved=[],notes='';try{const a=JSON.parse(localStorage.getItem(keys.plan)||'[]');if(Array.isArray(a))saved=caps.saved_list?a.filter(x=>typeof x==='string').slice(0,40):[];notes=localStorage.getItem(keys.notes)||'';}catch{}
  const today=new Date(),tomorrow=new Date();tomorrow.setDate(today.getDate()+1);const date=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  let trip={start:date(today),end:date(tomorrow),...region.config.trip_defaults};
  try{const x=JSON.parse(localStorage.getItem(keys.trip)||'{}');if(D.days(x.start,x.end)){trip.start=x.start;trip.end=x.end;}if(Object.hasOwn(D.activities,x.activity)||x.activity==='')trip.activity=x.activity;if(['Car / SUV','High-clearance vehicle','Truck with trailer','Motorhome / RV'].includes(x.vehicle))trip.vehicle=x.vehicle;}catch{}
  function records(){return new Map([...trails(),...D.camping(sites()),...sites().filter(f=>f.properties.site_type==='TRAILHEAD'),...(area?[area]:[])].map(f=>[f.properties.id,f]));}
  const persist=()=>{try{if(caps.saved_list){localStorage.setItem(keys.plan,JSON.stringify(saved));localStorage.setItem(keys.notes,notes);}localStorage.setItem(keys.trip,JSON.stringify(trip));}catch{$('summary').textContent='Browser storage unavailable; download your plan to keep it.';}};
  const paragraph=(box,text)=>box.append(el('p',text));
  const link=(label,url)=>{const node=el('a',label),safe=E.safeUrl(url);if(!safe)return el('p','Official link unavailable');node.href=safe;node.target='_blank';node.rel='noopener noreferrer';return node;};
  function download(filename,body,type){const u=URL.createObjectURL(new Blob([body],{type})),a=el('a');a.href=u;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);}
  function dialog(title){const node=el('dialog',undefined,'explore-dialog'),head=el('div',undefined,'explore-heading'),body=el('div'),close=button('×',()=>node.close());close.setAttribute('aria-label','Close '+title);head.append(el('h1',title),close);node.append(head,body);$('map').parentNode.append(node);node.addEventListener('close',()=>node.opener?.focus());return {node,body,show(){node.opener=document.activeElement;shell.openDialog(node);}};}
  const browser={body:el('div')},filters=el('details',undefined,'explore-filters');filters.append(el('summary','Filters'));browser.body.append(button('Results',()=>shell.showList($('list-body'))),filters);const plan=caps.saved_list?dialog('Saved research'):null,inputs={};
  function field(label,id,type,options,value){const row=el('label',label),input=el(type==='select'?'select':'input');input.id=id;if(type==='select')for(const [key,text] of options){const option=el('option',text);option.value=key;input.append(option);}else input.type=type;input.value=value;row.append(input);filters.append(row);inputs[id]=input;return input;}
  field('Find','mode','select',[['trails','Trails'],['camping','Camping'],['trailheads','Trailheads'],['other-sites','Other listed sites']],'trails');
  field('Activity','activity','select',[...Object.entries(D.activities),['','All activities']],trip.activity);
  field('Search name or trail number','query','search',[],'');field('From','start','date',[],trip.start);field('Through','end','date',[],trip.end);
  field('Camping vehicle','vehicle','select',['Car / SUV','High-clearance vehicle','Truck with trailer','Motorhome / RV'].map(x=>[x,x]),trip.vehicle);
  paragraph(filters,'Filters affect this list only. Trip dates are compared only with restricted dates from the source; other source dates are not evaluated. Camping vehicle suitability needs individual review. Nearby means within five straight-line miles, not a rideable connection.');
  const count=el('p'),results=el('div');count.id='count';count.setAttribute('role','status');results.id='results';browser.body.append(count,results);
  for(const [id,input] of Object.entries(inputs))input.oninput=()=>{if(Object.hasOwn(trip,id))trip[id]=input.value;persist();renderBrowse();};
  function show(f){plan?.node.close();shell.showDetail(f.properties.activities?trailEntry:siteEntry,f);}
  function result(f,extra){const node=button('',()=>show(f));node.className='explore-result';node.dataset.feature=f.properties.id;node.append(el('strong',name(f)+(f.properties.trail_number?' · #'+f.properties.trail_number:'')),el('small',extra||kind(f)));if(f.properties.activities&&trip.activity)node.append(el('span',D.season(f,trip.activity,trip.start,trip.end)));return node;}
  function renderBrowse(){const mode=inputs.mode.value,loaded=region.layers.get(mode==='trails'?trailEntry.id:siteEntry.id)?.state==='loaded',list=rows(trails(),sites(),area,mode,inputs.query.value,trip.activity),noun=mode==='trails'?'source segments':mode==='camping'?'camping listings (one area without a pin)':mode==='other-sites'?'other listed sites':'trailhead records';count.textContent=loaded?`${list.length} ${noun} · map layers unchanged`:'Could not load';results.replaceChildren(...list.map(f=>result(f,mode==='other-sites'?sourceType(f):undefined)));if(!list.length&&loaded)paragraph(results,'No matches in this inventory. Try a name, trail number or another activity.');}
  const notesField=el('textarea');notesField.id='feedback';notesField.rows=4;notesField.value=notes;notesField.oninput=()=>{notes=notesField.value;persist();};
  function showPlan(){const box=plan.body;box.replaceChildren();paragraph(box,'Saved on this browser only. No access or availability is confirmed.');const all=records();if(!saved.length)paragraph(box,'Save a trail or campground from its details to begin.');for(const id of saved){const f=all.get(id);if(f)box.append(button(name(f),()=>show(f)),button('Remove',()=>{saved=saved.filter(x=>x!==id);persist();showPlan();}));}const label=el('label','Field-test notes');label.append(notesField);box.append(label,button('Download plan & feedback',()=>download(region.config.export_names.plan,JSON.stringify(buildPlan(all,saved.filter(id=>all.has(id)),trip,notes,new Date().toISOString()),null,2),'application/json')));plan.show();}
  function render(){const box=$('list-body');box.replaceChildren(button('Find trails & camping',()=>{renderBrowse();shell.showList(browser.body);}),...(caps.saved_list?[button('Saved plan',showPlan)]:[]),button('Access & coverage notes',shell.showSources));
   const complete=region.layers.get(trailEntry.id)?.state==='loaded'&&region.layers.get(siteEntry.id)?.state==='loaded';
   if(complete){const all=records();saved=saved.filter(id=>all.has(id));$('summary').textContent=`${trails().length} trail segments · ${D.camping(sites()).length} campgrounds · ${sites().filter(f=>f.properties.site_type==='TRAILHEAD').length} trailheads · ${sites().filter(f=>!['CAMPGROUND','TRAILHEAD','DISPERSED_AREA'].includes(f.properties.site_type)).length} other listed sites. Closures unconfirmed.`;}else $('summary').textContent='Loading';
   if(shell.extrasFailed)paragraph(box,'Listings could not load');for(const id of saved){const f=records().get(id);if(f)box.append(result(f));}if(shell.isListActive(browser.body))renderBrowse();}
  function detail(entry,f,box,actions=box){
   if(!f.properties.activities&&!['CAMPGROUND','TRAILHEAD','DISPERSED_AREA'].includes(f.properties.site_type))return;
   const p=f.properties;box.append(link(p.activities||agencyPage(f)?'Official listing / source ↗':'Source data service ↗',source(f)));paragraph(actions,'Published source · current access unconfirmed');
   if(caps.saved_list){actions.append(button(saved.includes(p.id)?'Remove from saved':'Save to plan',()=>{if(saved.includes(p.id))saved=saved.filter(x=>x!==p.id);else if(saved.length<40)saved.push(p.id);persist();render();show(f);}));paragraph(actions,'Saving a place does not confirm it is suitable or available.');}
   if(p.activities&&caps.gpx_export){box.append(button('Download segment GPX',()=>download((p.trail_number||p.id)+'.gpx',D.gpx(f),'application/gpx+xml')));paragraph(box,'This is a county-clipped segment, not a complete route. GPX does not provide turn-by-turn guidance or confirm rideable connections.');}
   if(f.geometry?.type==='Point'){const [lon,lat]=f.geometry.coordinates;box.append(link('Directions to facility ↗',`https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`));paragraph(box,'Check approach roads and trailer parking before travel. Directions are for this facility, not a verified riding route.');}
   if(p.activities){box.append(el('h2',trip.activity?D.activities[trip.activity]:'Published activities'));if(trip.activity){paragraph(box,D.season(f,trip.activity,trip.start,trip.end));paragraph(box,'Ohvernight does not evaluate the managed, accepted or discouraged dates from the source for a trip. Dates the source does not list are unknown. The Motor Vehicle Use Map and current agency orders govern motor vehicle use.');}
    for(const [a,r] of Object.entries(p.activities)){if(trip.activity&&a!==trip.activity)continue;const rules=Object.entries(r).filter(([,v])=>v).map(([k,v])=>`${({managed:'source field "managed"',accpt:'source field "accepted"',disc:'source field "discouraged"',restricted:'source field "restricted"'})[k]}: ${v}`);if(rules.length)paragraph(box,D.activities[a]+': '+rules.join('; '));}
    paragraph(box,'These source dates can be incomplete or surprising. Verify the current motor-vehicle map and agency alerts. No difficulty, width, direction or bike-registration eligibility has been verified.');
    for(const [label,list] of [['Campgrounds nearby by straight-line distance',D.camping(sites())],['Trailheads nearby by straight-line distance',sites().filter(f=>f.properties.site_type==='TRAILHEAD')]]){box.append(el('h2',label));const nearby=list.map(x=>({f:x,d:T.distanceMiles(x.geometry.coordinates,f.geometry)})).filter(x=>x.d<=5).sort((a,b)=>a.d-b.d).slice(0,3);if(!nearby.length)paragraph(box,'None in this imported inventory within five straight-line miles.');nearby.forEach(x=>box.append(result(x.f,`${x.d.toFixed(1)} straight-line miles · connection unverified`)));}
   }else{for(const [key,label] of [['restrictions','Published restrictions'],['important_info','Important information'],['activity_type_list','Listed activities'],['fee_description','Fees (verify current price)'],['open_season','Published season (may be historical)'],['water_availability','Water'],['restroom_availability','Restrooms'],['directions','Agency directions']])if(p[key]&&p[key]!=='No Data'&&(agencyPage(f)||!DESCRIPTIVE.includes(key)))box.append(el('h2',label),el('p',p[key]));
    if(withheld(f))paragraph(box,WITHHELD);
    paragraph(box,'Stay limits, live availability and vehicle suitability are not verified. A nearby motorcycle trail does not permit riding an unlicensed bike through this campground.');if(f===area)paragraph(box,'Area listing only: individual campsites and access points have not been mapped.');
    if(f.geometry?.type==='Point'){box.append(el('h2','Trails for selected activity nearby by straight-line distance'));const near=trails().filter(x=>T.matches(x,'',trip.activity)).map(x=>({f:x,d:T.distanceMiles(f.geometry.coordinates,x.geometry)})).filter(x=>x.d<=5).sort((a,b)=>a.d-b.d).slice(0,5);near.forEach(x=>box.append(result(x.f,`${x.d.toFixed(1)} straight-line miles · connection unverified`)));if(!near.length)paragraph(box,'No matching imported segments within five straight-line miles.');}}
   box.append(button('Check alerts & coverage',shell.showSources));
  }
  return {render,detail,search(){renderBrowse();shell.showList(browser.body);},get trip(){return trip;},get saved(){return saved;}};
 }
 const api={rows,buildPlan,attach,agencyPage,withheld,DESCRIPTIVE,WITHHELD,kind};if(typeof module!=='undefined')module.exports=api;scope.ExploreBrowse=api;
})(typeof globalThis!=='undefined'?globalThis:this);
